#ifndef ERROR_H_INCLUDED
#define ERROR_H_INCLUDED
#endif

//Error Codes
#define INVALID_GCRYPT_VERSION 1
#define INVALID_FILE 2
#define CRYPT_INITIALIZATION_FAILED 3
#define ENCRYPTION_FAILED 4
#define INVALID_SYNTAX 5
#define OUTPUT_FILE_EXISTS 33
#define DECRYPTION_FAILED 5
#define INVALID_MAC 6
#define INVALID_SOCKET 7
#define INVALID_ADDR 8
#define CONNECTION_FAILED 9
